import type { WordPair } from '../types/game.js';

export const CATEGORIES = [
  'animals',
  'fruits',
  'vegetables',
  'food',
  'drinks',
  'sports',
  'vehicles',
  'places',
  'buildings',
  'weather',
  'music',
  'professions',
  'clothing',
  'technology',
  'nature',
] as const;

export type Category = (typeof CATEGORIES)[number];

export const WORD_PAIRS: WordPair[] = [
  { civilian: 'cat', spy: 'tiger', category: 'animals' },
  { civilian: 'dog', spy: 'wolf', category: 'animals' },
  { civilian: 'horse', spy: 'zebra', category: 'animals' },
  { civilian: 'cow', spy: 'bull', category: 'animals' },
  { civilian: 'pig', spy: 'boar', category: 'animals' },
  { civilian: 'sheep', spy: 'goat', category: 'animals' },
  { civilian: 'rabbit', spy: 'hare', category: 'animals' },
  { civilian: 'duck', spy: 'goose', category: 'animals' },
  { civilian: 'chicken', spy: 'turkey', category: 'animals' },
  { civilian: 'shark', spy: 'whale', category: 'animals' },
  { civilian: 'dolphin', spy: 'seal', category: 'animals' },
  { civilian: 'snake', spy: 'lizard', category: 'animals' },
  { civilian: 'frog', spy: 'toad', category: 'animals' },
  { civilian: 'bee', spy: 'wasp', category: 'animals' },
  { civilian: 'spider', spy: 'scorpion', category: 'animals' },
  { civilian: 'eagle', spy: 'hawk', category: 'animals' },
  { civilian: 'owl', spy: 'parrot', category: 'animals' },
  { civilian: 'monkey', spy: 'gorilla', category: 'animals' },
  { civilian: 'elephant', spy: 'rhino', category: 'animals' },
  { civilian: 'lion', spy: 'leopard', category: 'animals' },

  { civilian: 'apple', spy: 'pear', category: 'fruits' },
  { civilian: 'orange', spy: 'tangerine', category: 'fruits' },
  { civilian: 'banana', spy: 'plantain', category: 'fruits' },
  { civilian: 'grape', spy: 'raisin', category: 'fruits' },
  { civilian: 'watermelon', spy: 'cantaloupe', category: 'fruits' },
  { civilian: 'strawberry', spy: 'raspberry', category: 'fruits' },
  { civilian: 'blueberry', spy: 'blackberry', category: 'fruits' },
  { civilian: 'mango', spy: 'papaya', category: 'fruits' },
  { civilian: 'pineapple', spy: 'coconut', category: 'fruits' },
  { civilian: 'peach', spy: 'nectarine', category: 'fruits' },
  { civilian: 'cherry', spy: 'cranberry', category: 'fruits' },
  { civilian: 'lemon', spy: 'lime', category: 'fruits' },
  { civilian: 'kiwi', spy: 'pomegranate', category: 'fruits' },
  { civilian: 'plum', spy: 'apricot', category: 'fruits' },
  { civilian: 'fig', spy: 'date', category: 'fruits' },

  { civilian: 'carrot', spy: 'radish', category: 'vegetables' },
  { civilian: 'potato', spy: 'yam', category: 'vegetables' },
  { civilian: 'tomato', spy: 'pepper', category: 'vegetables' },
  { civilian: 'onion', spy: 'garlic', category: 'vegetables' },
  { civilian: 'lettuce', spy: 'spinach', category: 'vegetables' },
  { civilian: 'broccoli', spy: 'cauliflower', category: 'vegetables' },
  { civilian: 'corn', spy: 'peas', category: 'vegetables' },
  { civilian: 'pumpkin', spy: 'squash', category: 'vegetables' },
  { civilian: 'eggplant', spy: 'zucchini', category: 'vegetables' },
  { civilian: 'mushroom', spy: 'truffle', category: 'vegetables' },
  { civilian: 'asparagus', spy: 'celery', category: 'vegetables' },
  { civilian: 'cabbage', spy: 'kale', category: 'vegetables' },
  { civilian: 'beet', spy: 'turnip', category: 'vegetables' },
  { civilian: 'cucumber', spy: 'pickle', category: 'vegetables' },

  { civilian: 'burger', spy: 'sandwich', category: 'food' },
  { civilian: 'pizza', spy: 'pasta', category: 'food' },
  { civilian: 'salad', spy: 'soup', category: 'food' },
  { civilian: 'rice', spy: 'noodles', category: 'food' },
  { civilian: 'bread', spy: 'bagel', category: 'food' },
  { civilian: 'cake', spy: 'muffin', category: 'food' },
  { civilian: 'cookie', spy: 'cracker', category: 'food' },
  { civilian: 'pancake', spy: 'waffle', category: 'food' },
  { civilian: 'sushi', spy: 'ramen', category: 'food' },
  { civilian: 'taco', spy: 'burrito', category: 'food' },
  { civilian: 'steak', spy: 'roast', category: 'food' },
  { civilian: 'curry', spy: 'stew', category: 'food' },
  { civilian: 'donut', spy: 'croissant', category: 'food' },
  { civilian: 'cereal', spy: 'porridge', category: 'food' },
  { civilian: 'chocolate', spy: 'candy', category: 'food' },
  { civilian: 'cheese', spy: 'butter', category: 'food' },
  { civilian: 'yogurt', spy: 'pudding', category: 'food' },
  { civilian: 'honey', spy: 'syrup', category: 'food' },
  { civilian: 'omelette', spy: 'scramble', category: 'food' },
  { civilian: 'dumpling', spy: 'ravioli', category: 'food' },

  { civilian: 'coffee', spy: 'tea', category: 'drinks' },
  { civilian: 'milk', spy: 'cream', category: 'drinks' },
  { civilian: 'juice', spy: 'smoothie', category: 'drinks' },
  { civilian: 'water', spy: 'soda', category: 'drinks' },
  { civilian: 'beer', spy: 'ale', category: 'drinks' },
  { civilian: 'wine', spy: 'champagne', category: 'drinks' },
  { civilian: 'whiskey', spy: 'bourbon', category: 'drinks' },
  { civilian: 'vodka', spy: 'gin', category: 'drinks' },
  { civilian: 'rum', spy: 'tequila', category: 'drinks' },
  { civilian: 'cola', spy: 'lemonade', category: 'drinks' },
  { civilian: 'espresso', spy: 'latte', category: 'drinks' },
  { civilian: 'cappuccino', spy: 'americano', category: 'drinks' },
  { civilian: 'matcha', spy: 'chai', category: 'drinks' },
  { civilian: 'cider', spy: 'mead', category: 'drinks' },
  { civilian: 'cocktail', spy: 'mocktail', category: 'drinks' },

  { civilian: 'soccer', spy: 'basketball', category: 'sports' },
  { civilian: 'tennis', spy: 'badminton', category: 'sports' },
  { civilian: 'baseball', spy: 'cricket', category: 'sports' },
  { civilian: 'golf', spy: 'polo', category: 'sports' },
  { civilian: 'boxing', spy: 'wrestling', category: 'sports' },
  { civilian: 'swimming', spy: 'diving', category: 'sports' },
  { civilian: 'running', spy: 'jogging', category: 'sports' },
  { civilian: 'cycling', spy: 'skating', category: 'sports' },
  { civilian: 'skiing', spy: 'snowboarding', category: 'sports' },
  { civilian: 'surfing', spy: 'sailing', category: 'sports' },
  { civilian: 'hockey', spy: 'rugby', category: 'sports' },
  { civilian: 'volleyball', spy: 'handball', category: 'sports' },
  { civilian: 'archery', spy: 'fencing', category: 'sports' },
  { civilian: 'karate', spy: 'judo', category: 'sports' },
  { civilian: 'gymnastics', spy: 'ballet', category: 'sports' },

  { civilian: 'car', spy: 'truck', category: 'vehicles' },
  { civilian: 'bike', spy: 'scooter', category: 'vehicles' },
  { civilian: 'train', spy: 'subway', category: 'vehicles' },
  { civilian: 'bus', spy: 'van', category: 'vehicles' },
  { civilian: 'boat', spy: 'ship', category: 'vehicles' },
  { civilian: 'airplane', spy: 'helicopter', category: 'vehicles' },
  { civilian: 'motorcycle', spy: 'moped', category: 'vehicles' },
  { civilian: 'tractor', spy: 'bulldozer', category: 'vehicles' },
  { civilian: 'ambulance', spy: 'firetruck', category: 'vehicles' },
  { civilian: 'taxi', spy: 'limousine', category: 'vehicles' },
  { civilian: 'yacht', spy: 'canoe', category: 'vehicles' },
  { civilian: 'submarine', spy: 'rocket', category: 'vehicles' },
  { civilian: 'skateboard', spy: 'rollerblade', category: 'vehicles' },
  { civilian: 'tram', spy: 'trolley', category: 'vehicles' },
  { civilian: 'tank', spy: 'jeep', category: 'vehicles' },

  { civilian: 'beach', spy: 'desert', category: 'places' },
  { civilian: 'forest', spy: 'jungle', category: 'places' },
  { civilian: 'mountain', spy: 'hill', category: 'places' },
  { civilian: 'river', spy: 'lake', category: 'places' },
  { civilian: 'valley', spy: 'canyon', category: 'places' },
  { civilian: 'cave', spy: 'cliff', category: 'places' },
  { civilian: 'island', spy: 'peninsula', category: 'places' },
  { civilian: 'volcano', spy: 'glacier', category: 'places' },
  { civilian: 'swamp', spy: 'marsh', category: 'places' },
  { civilian: 'prairie', spy: 'savanna', category: 'places' },
  { civilian: 'ocean', spy: 'sea', category: 'places' },
  { civilian: 'waterfall', spy: 'geyser', category: 'places' },
  { civilian: 'meadow', spy: 'field', category: 'places' },
  { civilian: 'tundra', spy: 'steppe', category: 'places' },

  { civilian: 'hospital', spy: 'clinic', category: 'buildings' },
  { civilian: 'school', spy: 'university', category: 'buildings' },
  { civilian: 'library', spy: 'bookstore', category: 'buildings' },
  { civilian: 'museum', spy: 'gallery', category: 'buildings' },
  { civilian: 'church', spy: 'temple', category: 'buildings' },
  { civilian: 'castle', spy: 'palace', category: 'buildings' },
  { civilian: 'skyscraper', spy: 'tower', category: 'buildings' },
  { civilian: 'barn', spy: 'silo', category: 'buildings' },
  { civilian: 'warehouse', spy: 'factory', category: 'buildings' },
  { civilian: 'stadium', spy: 'arena', category: 'buildings' },
  { civilian: 'theater', spy: 'cinema', category: 'buildings' },
  { civilian: 'mall', spy: 'market', category: 'buildings' },
  { civilian: 'hotel', spy: 'motel', category: 'buildings' },
  { civilian: 'lighthouse', spy: 'windmill', category: 'buildings' },
  { civilian: 'prison', spy: 'courthouse', category: 'buildings' },

  { civilian: 'rain', spy: 'snow', category: 'weather' },
  { civilian: 'storm', spy: 'hurricane', category: 'weather' },
  { civilian: 'fog', spy: 'mist', category: 'weather' },
  { civilian: 'tornado', spy: 'cyclone', category: 'weather' },
  { civilian: 'thunder', spy: 'lightning', category: 'weather' },
  { civilian: 'sunshine', spy: 'moonlight', category: 'weather' },
  { civilian: 'drought', spy: 'flood', category: 'weather' },
  { civilian: 'frost', spy: 'hail', category: 'weather' },
  { civilian: 'breeze', spy: 'gale', category: 'weather' },
  { civilian: 'rainbow', spy: 'aurora', category: 'weather' },
  { civilian: 'drizzle', spy: 'shower', category: 'weather' },
  { civilian: 'heat', spy: 'humidity', category: 'weather' },

  { civilian: 'guitar', spy: 'violin', category: 'music' },
  { civilian: 'piano', spy: 'keyboard', category: 'music' },
  { civilian: 'drum', spy: 'tambourine', category: 'music' },
  { civilian: 'flute', spy: 'clarinet', category: 'music' },
  { civilian: 'trumpet', spy: 'saxophone', category: 'music' },
  { civilian: 'harp', spy: 'lyre', category: 'music' },
  { civilian: 'cello', spy: 'bass', category: 'music' },
  { civilian: 'banjo', spy: 'ukulele', category: 'music' },
  { civilian: 'accordion', spy: 'harmonica', category: 'music' },
  { civilian: 'xylophone', spy: 'marimba', category: 'music' },
  { civilian: 'bagpipe', spy: 'recorder', category: 'music' },
  { civilian: 'trombone', spy: 'tuba', category: 'music' },
  { civilian: 'mandolin', spy: 'sitar', category: 'music' },
  { civilian: 'organ', spy: 'synthesizer', category: 'music' },
  { civilian: 'oboe', spy: 'bassoon', category: 'music' },

  { civilian: 'doctor', spy: 'nurse', category: 'professions' },
  { civilian: 'teacher', spy: 'professor', category: 'professions' },
  { civilian: 'lawyer', spy: 'judge', category: 'professions' },
  { civilian: 'engineer', spy: 'architect', category: 'professions' },
  { civilian: 'chef', spy: 'baker', category: 'professions' },
  { civilian: 'pilot', spy: 'captain', category: 'professions' },
  { civilian: 'soldier', spy: 'officer', category: 'professions' },
  { civilian: 'farmer', spy: 'gardener', category: 'professions' },
  { civilian: 'painter', spy: 'sculptor', category: 'professions' },
  { civilian: 'writer', spy: 'journalist', category: 'professions' },
  { civilian: 'actor', spy: 'dancer', category: 'professions' },
  { civilian: 'musician', spy: 'singer', category: 'professions' },
  { civilian: 'scientist', spy: 'researcher', category: 'professions' },
  { civilian: 'plumber', spy: 'electrician', category: 'professions' },
  { civilian: 'carpenter', spy: 'mason', category: 'professions' },

  { civilian: 'shirt', spy: 'blouse', category: 'clothing' },
  { civilian: 'pants', spy: 'shorts', category: 'clothing' },
  { civilian: 'dress', spy: 'skirt', category: 'clothing' },
  { civilian: 'coat', spy: 'jacket', category: 'clothing' },
  { civilian: 'shoes', spy: 'boots', category: 'clothing' },
  { civilian: 'hat', spy: 'cap', category: 'clothing' },
  { civilian: 'gloves', spy: 'mittens', category: 'clothing' },
  { civilian: 'scarf', spy: 'shawl', category: 'clothing' },
  { civilian: 'tie', spy: 'bowtie', category: 'clothing' },
  { civilian: 'sweater', spy: 'hoodie', category: 'clothing' },
  { civilian: 'pajamas', spy: 'robe', category: 'clothing' },
  { civilian: 'swimsuit', spy: 'trunks', category: 'clothing' },
  { civilian: 'sandals', spy: 'slippers', category: 'clothing' },
  { civilian: 'socks', spy: 'stockings', category: 'clothing' },

  { civilian: 'computer', spy: 'laptop', category: 'technology' },
  { civilian: 'phone', spy: 'tablet', category: 'technology' },
  { civilian: 'camera', spy: 'binoculars', category: 'technology' },
  { civilian: 'headphones', spy: 'earbuds', category: 'technology' },
  { civilian: 'television', spy: 'projector', category: 'technology' },
  { civilian: 'printer', spy: 'scanner', category: 'technology' },
  { civilian: 'router', spy: 'modem', category: 'technology' },
  { civilian: 'smartwatch', spy: 'pedometer', category: 'technology' },
  { civilian: 'speaker', spy: 'microphone', category: 'technology' },
  { civilian: 'drone', spy: 'robot', category: 'technology' },
  { civilian: 'charger', spy: 'battery', category: 'technology' },
  { civilian: 'monitor', spy: 'screen', category: 'technology' },

  { civilian: 'tree', spy: 'bush', category: 'nature' },
  { civilian: 'flower', spy: 'weed', category: 'nature' },
  { civilian: 'grass', spy: 'moss', category: 'nature' },
  { civilian: 'leaf', spy: 'petal', category: 'nature' },
  { civilian: 'rock', spy: 'pebble', category: 'nature' },
  { civilian: 'sand', spy: 'dirt', category: 'nature' },
  { civilian: 'cloud', spy: 'smoke', category: 'nature' },
  { civilian: 'fire', spy: 'lava', category: 'nature' },
  { civilian: 'star', spy: 'planet', category: 'nature' },
  { civilian: 'moon', spy: 'sun', category: 'nature' },
  { civilian: 'stream', spy: 'brook', category: 'nature' },
  { civilian: 'seed', spy: 'sprout', category: 'nature' },
  { civilian: 'bark', spy: 'root', category: 'nature' },
  { civilian: 'fern', spy: 'cactus', category: 'nature' },
  { civilian: 'vine', spy: 'ivy', category: 'nature' },
];
